name: Unit tests

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          dotnet restore ./src/Unicorn.Taf.Core/Unicorn.Taf.Core.csproj
          dotnet restore ./src/Unicorn.UnitTests/Unicorn.UnitTests.csproj
      - name: Build
        run: dotnet build ./src/Unicorn.Taf.Core/Unicorn.Taf.Core.csproj --configuration Release
      - name: Test
        run: dotnet test ./src/Unicorn.UnitTests/Unicorn.UnitTests.csproj --configuration Release --framework net6.0 --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
