name: dotnet package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: |
          dotnet restore ./src/Unicorn.Taf.Core/Unicorn.Taf.Core.csproj
          dotnet restore ./src/Unicorn.UnitTests/Unicorn.UnitTests.csproj
      - name: Build
        run: dotnet build ./src/Unicorn.Taf.Core/Unicorn.Taf.Core.csproj
      - name: Test
        run: dotnet test ./src/Unicorn.UnitTests/Unicorn.UnitTests.csproj --framework net5.0 --verbosity normal --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ matrix.dotnet-version }}
          path: TestResults-${{ matrix.dotnet-version }}
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
